apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: grafana
    type: dashboard
  name: grafana-app
  namespace: monitoring
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: grafana
  template: 
    metadata: 
      labels: 
        app: grafana
    spec: 
      containers: 
       - image: "docker.io/grafana/grafana:5.0.0"
         name: grafana
         ports: 
          - containerPort: 3000
            name: http
         volumeMounts:
                - name:  grafanaconfigvolume
                  mountPath: /var/lib/grafana
      hostNetwork: true
      volumes:
           - name: grafanaconfigvolume
             hostPath:
                   path: /home/pinakmazumdar/monitoring/grafana
      securityContext:
        fsGroup: 472 
