apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"guestbook","tier":"frontend"},"name":"frontend","namespace":"default"},"spec":{"ports":[{"port":80}],"selector":{"app":"guestbook","tier":"frontend"},"type":"NodePort"}}
  labels:
    app: guestbook
    tier: frontend
  name: frontend
  namespace: cadvisor 
spec:
  ports:
  - port: 8080
  selector:
    app: guestbook
    tier: frontend
  type: NodePort
